name: Prometheus merger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #@daily
jobs:
  prometheus-merge:
    uses: rhobs/syncbot/.github/workflows/merge-flow.yaml@main
    with:
      upstream: prometheus/prometheus
      downstream: openshift/prometheus
      sandbox: rhobs/prometheus
      go-version: "1.20"
      restore-upstream: >-
        CHANGELOG.md
        VERSION
        go.mod
        go.sum
        .golangci.yml
      assets-cmd: |
        make assets-compress
        find web/ui/static -type f -name '*.gz' -exec git add {} \;
        git add web/ui/embed.go
        git diff --cached --exit-code || git commit -s -m "[bot] assets: generate"

    secrets:
      pr-app-id: ${{ secrets.APP_ID }}
      pr-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
      cloner-app-id: ${{ secrets.CLONER_APP_ID }}
      cloner-app-private-key: ${{ secrets.CLONER_APP_PRIVATE_KEY }}
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
